---
title: "Diffusion with Steps: The Adoption and Implementation of Laws about Violence Against Women"
author:
- affiliation: University of Iowa
  name: Woo, Byung-Deuk
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    keep_tex: no
    latex_engine: pdflatex
    template: svm-latex-ms2.tex
  html_document:
    df_print: paged
citecolor: black
biblio-style: apsr
endnote: no
fontsize: 11pt
keywords: Violence Against Women, Laws, Implementation, Women Political Empowerment, the percent of women in parliaments.
linkcolor: black
bibliography: 
  author: 
abstract: Violence Against Women (VAW) is a severe problem in the world, regardless of regime types, cultures, and the level of developemtn. However, many countries still lack of the very basic tool to regulate VAW. In this paper, I deal with why, when, and how countries adopt laws about violence against women. Moreover, I look at the implementation of that laws with several event history analysis including monadic, dyadic, and dyadic with steps models. I find out that women political empowerment increases the probability of adoption and implementation of laws about violence against women. Especially, the percent of women in parliaments influences on the probability of implementation of laws about violence against women. However, the percent of women in parliaments is not substantively significant.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load all the packages you will use below 
library(dotwhisker)
library(tidyverse)
```

Recently, Violence Against Women (VAW) has received great attention internationally and domestically. Despite various efforts to eradicate VAW, VAW still remains a severe problem not only in developing countries but also in developed countries. The absence of laws about VAW exacerbates this problem. Laws are the very basic tools to regulate VAW. However, there are still no specific answer about why countries adopt laws about VAW. This paper deals with the question: “Why, when, and how do countries adopt laws against VAW?”

However, countries cannot uproot VAW just by adopting laws about it. What is more important is a successful implementation. Even when there is a law for eliminating VAW, a presence of a law cannot deal with crimes against women (Askin 1997) without an appropriate implementation. Therefore, I deal with not only the first question but also the question: “why, when, and how do countries implement laws about VAW?” 

In this paper, I focus on the influences of women political empowerment and the percent of women in parliaments on the adoption and implementation of laws about VAW. In order to estimates the influences of them, I apply monadic, dyadic conditioned and dyadic diffusion with steps model. Because countries must adopt laws before they implement those laws, there are steps. In order to deal with those steps, I suggest dyadic diffusion with steps model and I show that this model is better than dyadic conditioned model.

I will discuss about the problem of VAW and several reasons why I focus on domestic laws rather than international laws or other domestic tools for regulating VAW. Then, theories, variables, and method sections will be presented before result section.

# Violence Against Women
Protecting women rights and empowering women have been a hotly debated topic for several decades (Carroll 1994; Rowlands 1997; Bunch 1990; Doepke et al. 2012; Duflo 2012; Hall 2013). Those articles focus on explaining why women right or women empowerment is far behind those of men. Protecting women rights is the pre-requisite of empowering women. Solid protection of women rights enables women to invest their time, effort, and talent to their works. As Watts and Zimmerman (2002), and Devries et al. (2013) point out, VAW is a serious problem in the world. VAW is a huge impediment to achieving gender equality. The absence of protection from VAW undermines the base of women empowerments. For example, if women in school or women in workplace are exposed to the risk of sexual violence or sexual harassment, they cannot fully exert their talents. Moreover, if there is no law about such crimes, it prevents women from seeking empowerment. Therefore, debates and researches about VAW should be preceded. 
In order to study adoption and implementation about VAW, we need to define what “women” means and what “Violence Against Women” is. In this article, I follow the definitions of “women” and “violence against women” from UN WOMEN.

\begin{center}
“The term “women” refers to females of all ages, including girls” (UN WOMEN).
\end{center}

According to the above definition, “women” is females regardless of all age. “Violence Against Women” is defined as below.

\begin{center}
“Any act of gender-based violence that results in, or is likely to result in, physical, sexual or psychological harm or suffering to women, including threats of such acts, coercion or arbitrary deprivation of liberty, whether occurring in public or in private life” (UN WOMEN).
\end{center}

Thus, “violence against women” has less broad meaning than “gender-based violence”. Those definitions help us to clarify what we study and focus on.

# Why laws, especially domestic laws? Why laws are not enough?
Law is the basic way to control violence, protect individual rights, and maintain social justice (Harel 2014). Even though interpretations of laws sometimes depend on social norms (Macnamara and Sagarin 1977), the absence of laws prevent us from discriminating whether certain behavior is punishable or not.

We can study adoption of constitution or regulation about VAW instead of law. However, there are methodological and substantive limitations for studying adoption of constitution or regulation. First, constitution is usually written or created when an individual country is built or gets independence. Moreover, constitutions are hard to be changed or revised (Bánkuti et al. 2012). Methodologically, it means that there are less variations in a dependent variable if I use adoptions or revisions of constitutions as a dependent variable. Substantively, implementation of constitution highly depends on judicial interpretation. Also, constitutions related to VAW usually expressed vary broadly without indicating which behaviors should be considered as violence. It makes proper implementation more difficult. 

It is hard to use regulation related to VAW. The OECD defines regulation as below.

\begin{center}
“imposition of rules by government, backed by the use of penalties that are intended specifically to modify the economic behavior our individuals and firms in the private sector. Various regulatory instruments or targets exist. Prices output, rate of return (in the form of profits, margins or commissions), disclosure of information, standards and ownership ceilings are among those frequently used” (OECD 2002).
\end{center}

It means that regulation includes laws, orders, norms, decrees, or other forms of administrative guidance (Black 2002). Using adoption of regulation means that we deal with the above legal forms equally. However, they have different legal powers and efficiency, even though the degrees of differences depend on individual countries’ legal systems. Thus, studying adoption and implementation of laws about VAW is more appropriate than studying those of constitutions or regulations.

There are domestic and international laws for controlling VAW. In this article, I deal with only adoption and implementation of domestic laws of individual countries instead of international laws because of the following reasons. International laws about VAW are usually related to war crimes, especially under armed conflicts (Chinkin 1994; Copelon 2000; Meron 1993; Edwards 2010). International laws usually do not deal with domestic VAW when there are no wars or armed conflicts. However, VAW are not problems only during wars or armed conflicts. VAW should be dealt even when there are no certain disturbances. In addition, international laws related to women’s rights and issues are marginalized (Johnson et al. 2008). Therefore, it is not sufficient ways to control VAW in individual countries yet. Secondly, international laws cannot be easily enforced due to lack of authority. Therefore, I will focus on the adoption and implementation of domestic laws rather than international laws. 

Laws are important because it is the starting point of eradicating VAW. Adopting laws about violence against women is valuable itself. However, laws lose their meanings under the lack of proper implementation. Neumann (2017) points out that traditional legal and bureaucratic strategies are not enough to eliminating VAW based on a case study in Nicaragua. Moreover, Karjane et al. (2005) find out that sexual assault is still a big problem in the United States despite of the presence of Federal law, “the Cleary Act of 1990 and the Campus Sexual Assault Victims’ Bill of Rights of 1992.” Thus, we must consider beyond the adoption of laws about VAW for taking advantages of existing laws. The next section deals with hypotheses related to women political empowerment and the percent of women in parliaments.

#Theory and Hypotheses: When, Why, and How Do Countries Adopt and Implement Laws about Violence Against Women?
When, why, and how do countries adopt laws about violence against women? In this article, I focus on the influence of women political empowerment on the adoption and implementation of laws about VAW. Women Political Empowerment can be divided into various components such as women’s rights and women’s freedom. Also, it is closely related to whether women can participate into the formal decision-making process in legislatures or executive branches. If women in a country can express their thoughts and opinions well and if there are efficient ways to reflect those things, gender related issues can be dealt more effectively. Based on this story, I will test the following hypotheses. 

\begin{center}
Hypothesis 1: Higher Women Political Empowerment increases the probability of adoption of laws about VAW.
\end{center}

\begin{center}
Hypothesis 2: Higher Women Political Empowerment increases the probability of implementation of laws about VAW.
\end{center}

To be specific, high percent of women in parliament can increase the probability of adoption and implementation of laws about VAW because of descriptive representation. Mansbridge (1999) develops the term “descriptive representation” which means the representation by representatives from their own persons. She argues that the benefits of selective descriptive representation outweigh the costs in certain conditions. The contexts of mistrust and uncrystallized interests are two main conditions when the selective descriptive representation enhances substantive representation.

Her theory can be applied to adoption and implementation of laws about violence against women. A long history of dominants from one specific group causes representatives to ignore or mistrust subordinate. Therefore, subordinate underrepresented continuously. In this case, shared experience can streamline conversations between descriptive representative and subordinate. Female has been alienated by male for a long time socially, politically, economically, and even academically, even though there are some differences in degrees in each country and culture. In this condition, female representatives can facilitate conversations with other females because they shared experiences as women. 

Moreover, as Mansbridge (1999) mentions in her article, gender issue is one of the uncrystallized interests relative to economic issues. In this early stage of issue development, the role of representatives is significant. Descriptive representation helps representatives to catch the main point of the issue related to their own groups. In the case of violence of women, women representatives can catch what is the problem and how to solve the problem by communicating with other women. Also, horizontal communications among representatives enables dispersion of the debate about violence against women and make other representatives to pay attention to the seriousness of it.

Other scholars also find the importance of female representatives. For example, Swers (2002) finds out that female legislators pay more attention on gender issues. Atkeson and Carrillo (2007) argue that female descriptive representation increases external efficacy. In addition, Tam (2017) finds out that female legislators in an undemocratic or semi-democratic legislature also more focus on women’s interests than male legislators do. 

Based on these previous studies, I will test the following hypothesis related to the percent of women in parliaments.

\begin{center}
Hypothesis 3: Higher percent of women in parliaments increases the probability of adoption and implementation of laws about VAW.
\end{center}

In the next section, I will discuss about variables for testing those three hypotheses.

# Variables
For testing the influence of women political empowerment and the percent of women in parliament on the probability of adoption and implementation of laws about VAW, I use two dependent variables: adoption of laws about violence against women and adoption of National Action Plan about the laws.

I use brand-new database for laws and National Action plan about violence against women from UN WOMEN GLOBAL Database ((UN WOMEN Global Database on Violence against Women  2016). This database provides data about when countries adopted laws and National Action Plan about violence against women. It deals with 191 countries in the world (List of countries in Appendix 1). 

VAW is subcategorized into Femicide, Forced Sterilization, Stalking, Domestic Violence & Intimate Partner Violence, Sexual Violence, Sexual Harassment, Female Genital Mutilation/cutting(FGM/C), Trafficking, Child Early and Forced Marriage, New Forms of Violence, and Violence related to Property.

\begin{center}
[Figure 1]
\end{center}

The first adoption of laws about VAW happened in 1908 by Japan. There is a S-curve related to the cumulative number of countries with laws about VAW. I use binary dependent variable for the adoption of laws about VAW. I assign 1 for country-year when a country adopts a law. On the other hand, I code country-year as 0.

However, as I mentioned in the previous section, the adoption of laws against VAW should not be the end stage. Successful implementation is more important than adopting laws for eradicating VAW. However, it is hard to conceptualize implementation and measure the level of implementation. 

I overcome this problem also by using data from UN women global database. In addition to laws, this database provides the list of countries which have National Action Plan for uprooting VAW. It provides explanation about National Action Plan as below. 

\begin{center}
“Laws on violence against women should require creation of a national action plan to eliminate violence against women. A national action plan can be extremely useful tool with which assess strengths and weaknesses, set targets, identify private organizations that can help implement new laws or priorities, and plot future initiatives to prevent violence against women. Action plans and strategies should also provide for consistent funding of implementation programs.” (UN WOMEN: United Nations Entity for Gender Equality and the Empowerment of Women)
\end{center}

Based on the above explanation, National Action Plan is a step toward successful implementation of laws about VAW. It includes several activities for implementing laws. I code 1 for country-year when the country builds National Action Plan. On the other hand, I assign 0. 

\begin{center}
[Figure 2]
\end{center}

Figure 2 shows the cumulative number of countries with NAP and the number of countries adopting NAP about VAW. As you can see, the first adoption of NAP happened in 1988 and the number of countries adopting NAP rapidly increased from 2004 to 2012. 

# Independent Variables
Missing data can cause biases and inefficiencies (Honaker and King 2010). Thus, I try to use dataset with large enough data span that can be used for testing my hypotheses. Below is a descriptive table for the variables in my research.

\begin{center}
[Table 1]
\end{center}

# Women political empowerment
I use V-Dem dataset (Coppedge et al. 2018) for testing whether there is a relationship between women political empowerment and the adoption and implementation of laws about VAW. V-Dem dataset defines women empowerment as below.

\begin{center}
We define women’s political empowerment as a process of increasing capacity for women, leading to greater choice, agency, and participation in societal decision-making. Our definition is three dimensional capturing the three most prominent strands in thinking on empowerment: that of choice, that of agency, and that of participation (Sundström et al. 2015).
\end{center}

The women political empowerment index from V-Dem covers countries from 1900 to present. It uses three equally-weighted dimensions of civil liberties, women’s open discussion and participation, and the level of presentation of women in political positions (Coppedge et al. 2018).

Moreover, I use separated indexes from World Bank for seeing the influence of the percent of women in parliaments. I use the separated indexes only for the adoption of NAP because the data span from World Bank is from 1990. 

# Major Episodes of Political Violence (MEPV) 
Countries might try to adopt and implement laws about VAW when they recognize the seriousness. In other words, countries will put legal efforts for eradicating VAW when there are many victims from it. I use Major Episodes of Political Violence (MEPV) dataset (Marshall 2017) in order to control the influence of political violence. This dataset provides violence score for each country from 1946 to 2016. I use total summed magnitudes of all societal and interstate MEPV score ranges from 0 to 20. The higher score indicates more violence.

# Polity2
For controlling the influence of regime types, I use polity score (Marshall et al. 2018) rather than Freedom House data. Selecting measurement about level of democracy should be considered seriously because it makes the results totally different (Högström 2013; Casper and Tufis 2002 ). Therefore, when select dataset about democracy, we need persuasive reasons based on research questions.

I choose polity score based on two main reasons. First, polity dataset has larger time span. Freedom House data covers only from 1972 to present. It is not enough for testing my hypothesis because the first adoption of law about VAW happened in 1908. On the other hand, polity dataset covers from 1800 to present (Marshall et al. 2002). Second, Freedom House dataset is criticized by scholars because of bias and less consistency. For example, Steiner (2016) argues that there is a substantial bias in the Freedom House score before 1988 and there is a less consistency after 1989.

Based on those two reasons, I use polity dataset in this research. Polity 2 score ranges from -10 to +10.

# CEDAW
As you can see on the cumulative graphs in figure 1 and figure 2, the number of adoptions of laws and implementation about violence against women increased after 1980s. There are several possible explanations for this trend.

First, This trend of adoptions can be related to the increased number of countries getting independence especially in Africa (Meredith 2005). However, the increased number of countries cannot fully explain the trend because there are still political and economic instability in African countries (Fosu 1992; Asiedu 2006; Lagi et al. 2011).

Second, world conferences on women can influence on the probability of adoption and implementations of laws about VAW. World conference on women have been held four times: Mexico City in 1975, Copenhagen in 1980, Nairobi in 1985, and Beijing in 1995. The agendas are related not only to human rights, but also to move women from periphery to center (Moghadam 1996; Bunch and Fried 1996). Especially, the Fourth World Conference on Women (FWCW) in Beijing was the largest conference on women and numerous Non-Governmental Organization participated to this conference. 

However, the main issue dealt in FWCW is not the VAW. Rather, it was focused on women health, working environment of women (WHO 1996), and women in the linkage between political and international economic situations (Agarwal 1996). Even though there were discussions about women rights, there are limitations. FWCW did not deal with women rights in countries where women rights are desperately needed. For example, several countries including Saudi Arabia, Granada, Somalia, Federal Republic of Yugoslavia do not attend the conference or were not invited (Otto 1996). 

Therefore, I concentrate on Convention on the Elimination of All Forms of Discrimination against Women (CEDAW) instead of those two possible explanations. CEDAW is the international treaty for eliminating all kinds of discrimination against women. Even though it does not deal with VAW directly, it deals with several forms of violence such as sexual violence and harassment. Therefore, if country joins CEDAW, we can guess that the country takes care about women related issues. Thus, I include a variable “CEDAW” as a dummy variable. I assign 1 for countries joining CEDAW. Otherwise, I assign 0.

# GDP per Capita
I get data about GDP per capita from Maddison Project Database (Bolt et al. 2018). Maddison Project Database has longer data span than any other data about GDP per capita. For example, World Bank provides GDP per capita data from 1960 to 2017. On the other hand, Maddison Project Database deals with GDP per capita of prior to 1960 (Smits et al. 2009). 

# Diffusion Variables
For diffusion variables, I use percentage of countries adopting laws and National Action Plan for regional diffusion, diffusion among countries with the same colonial heritage and legal system. I use the categories from the Quality Of Government 2018 standard dataset 2018 (Teorell et al. 2018). 

QOG categorizes colonial origin into ten subcategories: Never colonized by a Western overseas colonial power, Dutch, Spanish, Italian, US, British, French, Portuguese, Belgian, British-French, and Australian. For Geo-Political region, there are 10 subcategories: Eastern Europe and post Soviet Union, Latin America, North Africa & the Middle East, Sub-Saharan Africa Western Europe and North America, East Asia, South-East Asia, South Asia, The Pacific, and The Caribbean. 

There are five categories for legal origin: English Common Law, French Commercial Code, Socialist/Communist Laws, German Commercial Code, and Scandinavian Commercial Code. QOG dataset covers from 1946 to 2017. According to each country’s history, I fill up colonial heritage before 1946. For constructing diffusion, I divide number of countries with laws or NAP by total number of countries with same colonial heritage, same geo-political region, or legal system by year.

\begin{center}
[Figure 3]
\end{center}

Figure 3 shows the countries with laws about violence against women in 1966, 1986, 1996, and 2016. We can guess that there might be influences of diffusion among countries with the same region, colonial heritage, and legal system. 

\begin{center}
[Figure 4]
\end{center}

Figure 4 shows the countries with NAP about VAW. The patterns of colors for countries with laws and NAPs from Figure 3 and Figure 4 are different. Thus, I expect that the influences of diffusion variables on the probability of adoption of laws and NAPs are different.

In addition to those three diffusion variables, I include CEDAW (%). It is built by dividing total number of countries joining CEDAW by total number of countries. This is the variable to see the influence of pressures from international society on the probability of adoption and implementation of laws about VAW.

# Method
Policy diffusion researches has been conducted a lot in American Politics area based on rich resources and data (Walker 1969; Gray 1973; Mooney 2001; Savage 1985; Karch 2006; Mintrom and Vergari 1998; Shipan and Volden 2008). Most of topics deal with why, when, and how states adopt of various policies or laws. Not only in American Politics, but also policy diffusion is studied broadly in International Relations and Comparative Politics (Graham et al. 2012; Collier and Messick 1975; Radaelli 2007; Gilardi 2012; Graham et al. 2014; Gilardi et al. 2008).

Diffusion has been studied through event history analysis and scholars focus on various mechanisms behind diffusion. For example, Berry and Berry (1990) uses an event history analysis and they show that internal and external determinants, such as regional diffusion, models are compatible. Diffusion studied with an event history analysis has been developed in various ways. Boehmke (2009a) provides sophisticated modeling strategies dealing with multiple components such as pooled event history model that can be used for answering various questions. Some scholars combine additional models with an event history analysis. Pacheco (2012) uses a social contagion model and finds out mechanism of learning. Moreover, Marsh and Sharman (2009) find out that policy diffusion and policy transfer can be applied together and those two are complimentary. 

The most important advance in diffusion and event history analysis is the introduction of dyadic event history analysis. Previously, monadic approach is the main way to study diffusion and event history analysis. Volden (2006) opens a new way to study specific mechanisms behind diffusion such as emulation, learning, and competition. Dyadic event history analysis has been modified and developed. By using Monte Carlo analysis, Boehmke (2009b) finds out that we need to deal with a source of bias by removing observations with zero probability of emulation for more accurate estimation. Gilardi (2010) provides ways to consider heteroscedasticity possibly existing in dyadic level, each country in dyad, and year by using multilevel methods. Based on these contribution, dyadic event history analysis has been widely used for decade (Volden 2016; Gilardi 2008; Füglister 2011).

Gilardi (2016) provides four strategies for improving diffusion research. Based on his advices, I follow the existing definition of diffusion from Strang (1991): any kinds of processes that change the probability of adoption for the non-adopters. In this article, I deal with several questions related to when, why, and how countries adopt laws and implement them by using dyadic event history analysis for 191 countries from 1908 to 2016.

I apply several methods for testing my research hypotheses. First, I will use monadic event history analysis. In monadic event history analysis, the unit of analysis is country-year. By using this approach, I can test which kinds of variables affect the probability of adoption and implementation of laws. 

In addition to monadic approaches, I use dyadic event history analysis for testing the probability of emulation. In dyadic models, the unit of analysis is country A – county B – year. Based on Boehmke (2009b), I use conditioned dyadic event history model which eliminates observations with zero probability of emulation. Also, I combine pooled event history analysis and dyadic approach for testing my hypotheses.

\begin{center}
[Formula 1]
\end{center}

\begin{center}
[Formula 2]
\end{center}


The above formula is the directed dyadic model. Y_ijt means whether country “i” emulates country “j” at time “t” or not. Thus, Y_ijt=1 means country “i” adopts NAP by emulating country “j”. However, the directed dyadic model does not deal with emulation bias that Boehmke (2009b) mentioned. 

\begin{center}
[Formula 3]
\end{center}

Therefore, I use Dyadic Conditioned model (Formula (3)) for dealing with emulation bias. N_ijt=1 means that country “j” has NAP at time “t”. Thus, it drops observations if country “j” does not have NAP because there is a zero probability to being emulated by country “i”.

However, this model also does not deal with diffusion with steps. For investigating questions about why, when, and how countries implement laws about violence against women, I model dyadic diffusion with steps. Countries need to adopt laws first before they implement them. In other words, countries without laws cannot implement that laws logically. Thus, if we include observations about countries before adopting laws, we introduce bias and make coefficient inefficient. Therefore, I exclude observations without laws about violence against women.

\begin{center}
[Formula 4]
\end{center}

Basically, I subset the observations by adding one simple condition L_ijt=1 which means country “i” has laws about VAW at time “t”. It logically makes sense because countries cannot adopt NAP without adoption of law about VAW. Adding one more condition does not mean that I lose information because county “I” has zero probability of emulating country “j” when country “I” does not have laws: L_ijt= 0.

For showing the differences between the two models from formula (3) and (4), I conduct Monte Carlo simulation. Monte Carlo simulation is widely used for showing the differences among models and select the better model. I build reference model based on the monadic structure because dyadic models can increase the probability of type 1 error.

\begin{center}
[Formula 5]
\end{center}

\begin{center}
[Formula 6]
\end{center}

I use real data about “Women Political Empowerment for 191 countries from 1908 to 2016 as independent variable in Formula (5). Moreover, I build Y as binary variable because the adoption of laws about VAW is dummy variable.

\begin{center}
[Formula 7]
\end{center}

\begin{center}
[Formula 8]
\end{center}

Formula (7) and (8) are for building structures related to diffusion with steps. Basically, formula (8) means subsampling by adding one condition: “Y=1”. Based on this structure and 1,000 simulations, I compare “Dyadic Conditioned” model from formula (3) and “Dyadic Diffusion with Steps” model from formula (4).

\begin{center}
[Figure 5]
\end{center}

Figure 5 shows that the estimated coefficients of independent variable from the two models. As you can see, the simulated Beta of independent variable from “Dyadic Diffusion with Steps” is closer to Simulated Beta from “Reference” model. In other words, “Dyadic Diffusion with Steps” model reduces the potential bias a lot. Moreover, this model can correct the inferences.

\begin{center}
[Figure 6]
\end{center}

Figure 6 shows the simulated test statistics from “Reference”, “Dyadic Conditioned”, and “Dyadic Diffusion with Steps” models. Based on the result from “Reference” model, Women Political Empowerment does not has statistically significant relationship with “S”. However, the result from “Dyadic Conditioned” says that it is statistically significant which is wrong inference. On the other hands, the simulated T-statistics from “Dyadic Diffusion with Steps” model shows that there is no statistically significant relationship between Women Political Empowerment and “S”. Therefore, “Dyadic Diffusion with Steps” model is more appropriate when we deal with diffusions including steps (See Appendix 2 for detailed information about Monte Carlo simulation). 

# Result
Table 2 shows the results of four models about diffusion of laws about violence against women. Model 1 shows the result of the monadic event history analysis without diffusion variables and Model 2 is the result of the monadic event history analysis with diffusion variables. In Model 1 and Model 2, the unit of analysis is country – year. On the other hand, the unit of analysis in Model 3 and Model 4 is Dyad – Year, because those two models are directed dyadic models. The four models show slightly different results with different coefficients and standard deviations.

As you can see, women political empowerment, political violence (MEPV), and regional diffusion have statistically significant positive relationships with the probability of adoption or emulation of laws about VAW. Moreover, the absolute difference of polity2 in a dyad has statistically significant negative relationships with the probability of emulation of laws about VAW. It means that a country has higher probability of emulating other countries having similar political regime type. GDP per capita shows significant relationship except Model 2. On the other hands, Polity2, CEDAW, Colonial Heritage for Law (%), Legal System for Law (%), CEDAW (%), and GDP Difference are not statistically significant in all four models. 

Those results support the hypothesis that women political empowerment increases the probability of adoption and emulation of laws about VAW. You can see results from models with separate forms of violence in appendix (See Appendix 3), and Pooled Event History Analysis (See Appendix 4).

\begin{center}
[Table 2]
\end{center}

As mentioned in previous sections, it is more important to see whether countries do implement laws about VAW. Table 3 shows the results of four models related to the adoption NAP about VAW. Model 1 is the simple monadic event history model and Model 2 is a model considering steps of diffusion. In those two models, the unit of analysis is country – year. The results from Model 1 and Model 2 show that Women Political Empowerment is statistically significant. However, diffusion variables are not statistically significant except CEDAW (%) in Model2. 

\begin{center}
[Table 3]
\end{center}

Model 3 is Dyadic Conditioned model which eliminates observations with zero probability of emulation. The unit of analysis is dyad-year Model 4 shows the result of Dyadic Diffusion with Steps model. As expected, the coefficietns and standard errors of vindependent variables are different. CEDAW (%) is statistically significant in Model 2,Model3 , and Model 4. On the other hands, the women political empowerment has statistically significant relationship with the probability of adoption or emulation of NAP in all four models. Resutls from the four models also support the hypothesis that women political empowerment increaess the probability of implementation of laws aboutVAW.

\begin{center}
[Table 4]
\end{center}

To test hypothesis about the percentage of women in parliaments, I use three separated indexes which are the percentage of women in parliaments, the percentage of female employment, and the gross percentage of female primary education, from World Bank. Because the first adoption of NAP happened in 1988, results from Table 3 based on the data about 191 countries from 1988 to 2016. I use same four models in Table 3 but with separated indexes instead of women political empowerment from V-Dem. As you can see percent of women in parliaments is statistically significant at the level of p<0.05 in all four models. Moreover, the percent of countries with CEDAW is statistically significant at the level of p<0.001. However, other independent variables are not statistically significant. Moreover, the coefficients and standard errors are slightly different among four models, as expected.

\begin{center}
[Figure 7]
\end{center}

For checking whether the percentage of women in parliaments is substantively significant or not, I compare the marginal effects of the percentage of women in parliaments in the four models in Table 4. Figure 7 shows the marginal effects from the four models, holding other independent variables at their mean value. The marginal effects change across the four models. Based on the plots in Figure 7, it is hard to say that the percentage of women in parliaments is substantively significant because 20% increase in the percentage of women in parliaments only slightly increases the probability of adoption or emulation of NAP. Thus, this result does not support my hypothesis related to the percentage of women in parliaments (Also see Appendix 5 for results from Heckman Probit and Instrumental Variable Regression. However, it does not mean that descriptive representation does not work because adoption of NAP is executive function. Therefore, the percentage of women in executive branches. might be more influential on adoption of NAP rather than that of women in parliaments.

To sum up, the results from Table 2 and Table 3 show that women political empowerment increases the probability of adoption or emulation of laws and NAPs about VAW, which supports hypotheses 1 and 2. However, the result of Table 4 does not support hypothesis 3 but we can guess that the percentage of women in executive branches influences the adoption or emulation of NAP.

# Discussions and Conclusion
Nowadays, still a lot of women suffer from violence including sexual violence, sexual harassment, violence from intimate partner, trafficking, etc., even though international organizations and international non-governmental organizations have put emphasis on violence against women and lots of countries achieve certain level of economic development. Laws are the very basic tool for regulating violence against women and violence against women is closely related to women rights in countries. This paper firstly attempts to find out the reasons behind the adoption and implementation of laws about violence against women. Based on affluent and brand-new data from UN, I delve into the influences of women political empowerment and the percent of women in parliaments. 

All the models that I use in this paper show us that the women political empowerment has statistically significant relationship with the probability of adoption or emulation of laws and NAPs about VAW. On the other hands, even though the percent of women in parliaments is statistically significant with the probability of adoption and emulation of NAPs about VAW, it is not substantively significant for the probability of adoption and implementation of laws about VAW. However, it does not mean that descriptive representation does not matter because in this paper I only use the percent of women in parliaments rather than in other branches such as executive branches closely related to policy making.

Future researches should be researches for finding out the influences various forms of descriptive representation over parliaments on the ways to regulate VAW. Moreover, even though it is not dealt in this paper, activities of INGO and international organizations may influence on the countries’ effort to eradicate VAW. I hope that my research can provide a way to study VAW.

# References
Agarwal, Bina. 1996. "From Mexico 1975 to Beijing 1995." Indian Journal of Gender Studies Vol. 3:1.

Asiedu, Elizabeth. 2006. "Foreign direct investment in Africa: The role of natural resources, market size, government policy, institutions and political instability." World Economy Vol. 29 (Issue. 1):63-77.

Askin, Kelly Dawn. 1997. War Crimes Against Women.

Atkeson, Lonna Rae, and Nancy Carrillo. 2007. "More is Better: The Influence of Collective Female Descriptive Representation on External Efficacy." Politics & Gender Vol. 3 (Issue 1):pp. 79-101.

Bánkuti, Miklós, Gábor Halmai, and Kim Lane Scheppele. 2012. "Hungary’s Illiberal Turn: Disabling the Constitution " Journal of Democracy Vol. 23 (No. 3):138-46.

Berry, Frances Stokes, and William D. Berry. 1990. "State Lottery Adoptions as Policy Innovations: An Event History Analysis." American Political Science Revew Vol. 84 (Issue. 2):395-415.

Black, Julia. 2002. "Critical Reflections on Regulation, 27."

Boehmke, Frederick J. 2009a. "Approaches to Modeling the Adoption and Diffusion of Policies with Multiple Components " State Politics & Policy Quarterly Vol.9 (Issue 2):229-52.

———. 2009b. "Policy Emulation or Policy Convergence? Potential Ambiguities in the Dyadic Event History Approach to State Policy Emulation." The Journal of Politics Vol. 71 (No. 3):1125-40.

Bolt, Jutta, Robert Inklaar

Herman de Jong, and Jan Luiten van Zamden. 2018. "REBASING 'MADDISON': NEW INCOME COMPARISONS AND THE SHAPE OF LONG-RUN ECONOMIC DEVELOPMENT."

Bunch, Charlotte. 1990. "Women's Rights as Human Rights: Toward a ReVision of Human Rights." Human Rights Quarterly 12:486-98.

Bunch, Charlotte, and Susana Fried. 1996. "Beijing '95: Moving Women's Human Rights from Margin to Center." Journal of Women in Culture and Society Vol. 22 (Number 1).

Carroll, Susan. 1994. Women as Candidates in American Politics.

Casper, Gretchen, and Claudiu Tufis. 2002 "Correlation versus Interchangeability: The Limited Robustness of Empirical Findings on Democracy using Highly Correlated Datasetsi " Political Analysis Vol. 11 (Issue 2(R)).

Chinkin, Christine. 1994. "Rape and Sexual Abuse of Women in International Law." European Journal of International Law:326-41.

Collier, David, and Richard E. Messick. 1975. "Prerequisites Versus Diffusion: Testing Alternative Explanations of Social Security Adoption." American Political Science Review Vol. 69 (Issue 4):1299-315.

Copelon, R. 2000. "Gender Crimes as War Crimes: Integrating Crimes against Women into International Criminal Law." McGill law journal. Revue de droit de McGill 46(1):217-40.

Coppedge, Michael, John Gerring, Carl Henrik Knutsen, Staffan I. Lindberg, Svend-Erik Skaaning, Jan Teorell, David Altman, Michael Bernhard, Agnes Cornell, M. Steven Fish, Haakon Gjerløw, Adam Glynn, Allen Hicken, Joshua Krusell,Anna Lührmann, Kyle L. Marquardt, Kelly McMann, Valeriya Mechkova, Moa Olin, Pamela Paxton, Daniel Pemstein, Brigitte Seim, Rachel Sigman, Jeffrey Staton, Aksel Sundström, Eitan Tzelgov, Luca Uberti, Yi-ting Wang, Tore Wig, and Daniel Ziblatt. 2018. ""V-Dem Codebook v8" Varieties of Democracy (V-Dem)."

Devries, K. M., J. Y. T. Mak, C. Garcia-Moreno, M. Petzold, J. C. Child, G. Falder, S. Lim, L. J. Bacchus, R. E. Engell, L. Rosenfeld, C. Pallitto, T. Vos, N. Abrahams, and C. H. Watts. 2013. "The Global Prevalence of Intimate Partner Violence Against Women." Science Vol. 340 (Issue 6140):1527-8.

Doepke, Matthias, Michèle Tertilt, and Alessandra Voena. 2012. "The Economics and Politics of Women's Rights." Annual Review of Economics Vol. 4:339-72.

Duflo, Esther. 2012. "Women Empowerment and Economic Development." Journal of Economic Literature Vol. 50 (No. 4):1051-79.

Edwards, Alice. 2010. Violence against Women under International Human Rights Law: Cambridge University Press.

Fosu, Augustin Kwasi. 1992. "Political instability and economic growth: evidence from Sub-Saharan Africa." Economic Development and Cultural Change Vol. 40 (Issue. 4):829-41.

Füglister, Katharina. 2011. "Where does learning take place? The role of intergovernmental cooperation in policy diffusion." European Journal of Political Research Vol. 51 (Issue 3):316-49.

Gilardi, Fabrizio. 2010. "Who Learns from What in Policy Diffusion Processes?" American Journal of Political Science Vol. 54 (No. 3):650-66.

———. 2012. Transnational Diffusion: Norms, Ideas, and Policies. Edited by W. Carlsnaes, T. Risse and B. Simmons. Vol. 453-77. Los Angeles, CA: SAGE.

———. 2016. "Four Ways We can Improve Policy Diffusion Research." State Politics & Policy Quarterly Vol.16(1):8-21.
Gilardi, Fabrizio, Katharina Füglister, and Stéphane Luyet. 2008. "Learning from Others: The Diffusion of Hospital Financing Reforms in OECD Countries." Comparative Political Studies Vol 42 (Issue 4):549-73.

Gilardi, Farbrizio. 2008. "Empirical Modeling of Policy Diffusion in Federal States: The Dyadic Approach." Swiss Political Science Review 14(3):413-50.

Graham, Erin R., Charles R. Shipan, and Craig Volden. 2012. "The Diffusion of Policy Diffusion Research in Political Science." Brithish Journal of Political Science Vol. 43 (Issue 3):673-701.

———. 2014. "The Communication of Ideas across Subfields in Political Science." Political Science & Politics 47 (2):468-76.

Gray, Virginia. 1973. "Innovation in the States: A Diffusion Study." American Political Science Revew 67 (4):1174-85.

Hall, C. Margaret. 2013. Women and Empowerment: Strategies for Increasing Autonomy. 270 Madison Ave, New York NY 10016: Taylor & Francis.

Harel, Alon. 2014. Why Law Matters: Oxford University Press.

Högström, John. 2013. "Does the Choice of Democracy Measure Matter? Comparisons between the Two Leading Democracy Indices, Freedom House and Polity IV." Government and Opposition Volume 48 ( Issue 2 ).

Honaker, James, and Gary King. 2010. "What to Do about Missing Values in Time‐Series Cross‐Section Data." American Journal of Political Science Vol. 54 (Issue. 2):561-81.

Jann, Ben. 2017. "Plotting regression coefficients and other estimates in Stata." University of Bern.

Johnson, Holly, Natalia Ollus, and Sami Nevala. 2008. Violence against women: an international perspective. New York: Springer.

Karch, Andrew. 2006. "National Intervention and the Diffusion of Policy Innovations." American Politics Research Vol. 34 (Issue. 4):403-26.

Karjane, Heather M., Bonnie S. Fisher, and Farancis T. Cullen. 2005. "Sexual Assault on Campus: What Colleges and Universities Are Doing About It." Washington, DC 20531: National Institute of Justice (NIJ).

Lagi, Marco, Karla Z Bertrand, and Yaneer Bar-Yam. 2011. "The food crises and political instability in North Africa and the Middle East." Avilable at SSRN: https://ssrn.com/abstract=1910031 or http://dx.doi.org/10.2139/ssrn.1910031.

Macnamara, D E J, and E Sagarin. 1977. SEX, CRIME, AND THE LAW. New Work, NY 10020: Free Press.

Mansbridge, Jane. 1999. "Should Blacks Represent Blacks and Women Represent Women? A Contingent 'Yes'." Journal of Politics 61(3):628-57.

Marsh, David, and J.C. Sharman. 2009. "Policy diffusion and policy transfer." Policy Studies Vol. 30 (Issue 3):269-88.

Marshall, Monty G. 2017. "MAJOR EPISODES OF POLITICAL VIOLENCE (MEPV) AND CONFLICT REGIONS, 1946-2016." ed. C. f. S. Peace.

Marshall, Monty G., Ted Robert Gurr, Christian Davenport, and Keith Jaggers. 2002. "POLITY IV, 1800-1999 Comments on Munck and Verkuilen." Comparative Political Studies Vol. 35 (No. 1):40-5.

Marshall, Monty G., Ted Robert Gurr, and Keith Jaggers. 2018. "Political Regime Characteristics and Transitions, 1800-2017."

Meredith, Martin. 2005. The State of Africa: A History of Fifty Years of Independence: Free Press.

Meron, Theodor. 1993. "Rape as a Crime under International Humanitarian Law." American Journal of International Law Vol. 87 (Issue. 3):424-8.

Mintrom, Michael, and Sandra Vergari. 1998. "Policy Networks and Innovation Diffusion: The Case of State Education Reforms." The Journal of Politics Vol. 60 (Issue. 1):126-48.

Moghadam, Valentine M. 1996. "The Fourth World Conference on Women: Dissension and Consensus." Indian Journal of Gender Studies Vol. 3:1 

Mooney, Christopher Z. 2001. "Modeling Regional Effects on State Policy Diffusion." Political Research Quarterly Vol. 54 (Issue. 1):103-24.

Neumann, Pamela. 2017. "When Laws Are Not Enough: Violence against Women and Bureaucratic Practice in Nicaragua." Social Forces Vol. 95 (Issue 3):1105-25.

OECD. GLOSSARY OF STATISTICAL TERMS  2002 [cited.

Otto, Dianne. 1996. "Holding up Half the Sky, but for Whose Benefit: A Critical Analysis of the Fourth World Conference on Women " Australian Feminist Law Journal Vol. 6.

Pacheco, Julianna. 2012. "The Social Contagion Model: Exploring the Role of Public Opinion on the Diffusion of Antismoking Legislation across the American States." The Journal of Politics Vol. 74 (Number 1):187-202.

Radaelli, Claudio M. 2007. "Diffusion without convergence: how political context shapes the adoption of regulatory impact assessment." Journal of European Public Policy Vol. 12 (Issue. 5):924-43.

Rowlands, Jo. 1997. Questioning Empowerment working with Women in Honduras: Oxfam.

Savage, Robert L. 1985. "Diffusion Research Traditions and the Spread of Policy Innovations in a Federal System." Publius 15 (4):61-82.

Shipan, Charles R., and Craig Volden. 2008. "The Mechanisms of Policy Diffusion." American Journal of Political Science Vol. 52 (Issue 4):840-57.

Smits, J.P., P.J. Woltjer, and D. Ma. 2009. "A Dataset on Comparative Historical National Accounts, ca. 1870-1950: A Time-Series Pespective." ed. G. U. o. G. Groningen Growth and Development Centre Research Memorandum GD-107.

Steiner, Nils D. 2016. "Comparing Freedom House Democracy Scores to Alternative Indices and Testing for Political Bias: Are US Allies Rated as More Democratic by Freedom House?" Journal of Comparative Policy Analysis: Research and Practice Vol. 18 (Issue 4).

Strang, David. 1991. "Adding Social Structure to Diffusion Models: An Event History Framework." Sociological Methods & Research Vol.19 (3):324-53.

Sundström, Aksel, Pamela Paxton, Yi-ting Wang, and Staffan I. Lindberg. 2015. "Women;s Political Empowerment: A New Global Index, 1900-2012." ed. V.-D. institute.

Swers, Michele. 2002. The Difference Women Make: University of Chicago Press.

Teorell, Jan, Stefan Dahlberg, Sören Holmberg, Bo Rothstein, Natalia Alvarado, and Pachon & Richard Svensson. 2018. "The Quality of Government Standard Dataset, version Jan18." ed. U. o. G. T. Q. o. G. Institute.

UN WOMEN Global Database on Violence against Women.  2016 [cited. Available from http://evaw-global-database.unwomen.org/fr/about.

Volden, Craig. 2006. "States as Policy Laboratories: Emulating Success in the Children's Health Insurance Program." American Journal of Political Science Vol. 50 (Issue 2):294-312.

———. 2016. "Failures: Diffusion, Learning, and Policy Abandonment." State Politics & Policy Quarterly Vol. 16 ((1)):44-77.

Walker, Jack L. 1969. "The Diffusion of Innovations among the American States." American Political Science Revew 63 (3):880-99.

Watts, Charlotte, and Cathy Zimmerman. 2002. "Violence against women: global scope and magnitude." The Lancet Vol. 359 (Issue 9313):1232-7.

WHO. 1996. "Women's Health Day, 5 September 1995, at the fourth World Conference on Women, Beijing, People's Republic of China." ed. W. H. Organization.








